name: thingsboard_app
description: Flutter ThingsBoard Mobile Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.2

environment:
  #sdk: ">=2.12.0 <3.0.0"
   sdk: '>=2.19.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  thingsboard_client: 1.0.6
  intl: ^0.18.1
  flutter_secure_storage: ^9.0.0
  flutter_speed_dial: ^7.0.0
  cupertino_icons: ^1.0.2
  fluro: ^2.0.3
  flutter_svg: ^2.0.7
  auto_size_text: ^3.0.0-nullsafety.0
  infinite_scroll_pagination: ^4.0.0
  fading_edge_scrollview: ^3.0.0
  stream_transform: ^2.0.0
  flutter_inappwebview:
    git:
      url: https://github.com/rshrc/flutter_inappwebview
      ref: master
#  flutter_downloader: ^1.6.0
#  permission_handler: ^8.0.0+2
#  path_provider: ^2.0.2
  url_launcher: ^6.0.3
  image_picker: ^1.0.3
  mime: ^1.0.0
  logger: ^2.0.1
  qr_code_scanner: ^1.0.0
  device_info_plus: ^9.0.3
  geolocator: ^10.0.0
  material_design_icons_flutter: ^7.0.7296
  package_info: ^2.0.2
  dart_jsonwebtoken: ^2.2.0
  crypto: ^3.0.1
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^9.0.0
  universal_html: ^2.0.8
  universal_platform: ^1.0.0+1
  preload_page_view: ^0.2.0
  flutter_localizations:
    sdk: flutter
  firebase_messaging: ^14.6.7
  notification_permissions: ^0.6.1
  firebase_core: ^2.15.1
  flutter_local_notifications: ^15.1.1
  package_info_plus: ^4.2.0
  flutter_udid: ^2.0.1
  barcode_scan2: ^4.2.4
dependency_overrides:
  intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
     - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/thingsboard.png"
flutter_intl:
  enabled: true
